//SE AGREGARAN MAS A MEDIDA DE QUE SE VAYAN HACIENDO COMPONENTES....
export const CREAR_ESPECIALISTA="CREAR_ESPECIALISTA";
export const CREAR_PACIENTE="CREAR_PACIENTE";
export const OBTENER_ESPECIALIDADES="OBTENER_ESPECIALIDADES";
export const OBTENER_ESPECIALISTAS="OBTENER_ESPECIALISTAS";
export const OBTENER_PACIENTES="OBTENER_PACIENTES";
export const OBTENER_ESPECIALISTA_POR_NOMBRE="OBTENER_ESPECIALISTA_POR_NOMBRE";
export const ESPECIALISTA_DETALLADO="ESPECIALISTA_DETALLADO";
export const OBTENER_PACIENTE_POR_NOMBRE="OBTENER_PACIENTE_POR_NOMBRE";
export const PACIENTE_DETALLADO="PACIENTE_DETALLADO";
export const OBTENER_ESPECIALISTA_POR_ESPECIALIDAD="OBTENER_ESPECIALISTA_POR_ESPECIALIDAD";
export const RESETEAR_BUSQUEDA_ESPECIALISTA="RESETEAR_BUSQUEDA_ESPECIALISTA";
export const PAGINADO="PAGINADO";
export const ROL="ROL";